---
# tasks file for ansible-role-ansible-dev

- name: install packages
  apt:
    update-cache: yes
    force_apt_get: yes
    name:
      - python-setuptools
      - python3-pip
      - python3-venv
      - libssl-dev
      - python3-docker
  become: true

- name: block ansible packages in apt
  copy:
    src: ansible_apt-preferences
    dest: /etc/apt/preferences.d/
    owner: root
    group: root
    mode: 0644
  become: true

- name: configure pip behind a proxy if needed
  copy:
    src: pip.config
    dest: "/home//{{ item }}/.venv-ansible/pip.config"
  loop: "{{ developers }}"
  become: true
  when: proxy_env is defined

- name: setup virtual environments
  pip:
    virtualenv: "/home/{{ item }}/.venv-ansible"
    virtualenv_command: "/usr/bin/python3 -m venv"
    name: "{{ pip_packages }}"
  loop: "{{ developers }}"
  environment: "{{ proxy_env | default({}) }}"
  notify: "set ownership of virtual environments"
  become: true
