---
# tasks file for ansible-role-ansible-dev

- name: install packages
  apt:
    update-cache: yes
    force_apt_get: yes
    name:
      - python3-pip
      - python3-venv
      - libssl-dev
      - python3-docker
  become: true

- name: block ansible packages in apt
  copy:
    src: ansible_apt-preferences
    dest: /etc/apt/preferences.d/
    owner: root
    group: root
    mode: 0644
  become: true

- name: setup virtual environments
  pip:
    name: 
      - setuptools
      - ansible=={{ pip_version["ansible"] }}
      - molecule=={{ pip_version["molecule"] }}
    virtualenv: "/home//{{ item }}/.venv-ansible"
    virtualenv_command: "/usr/bin/python3 -m venv"
  loop: "{{ users }}"
  become: true

- name: set ownership of virtual environments
  file:
    path: "/home/{{ item}}/.venv-ansible"
    recurse: yes
    owner: "{{ item }}"
    group: "{{ item }}"
  loop: "{{ users }}"
  become: true
