---
# handlers file for ansible-role-ansible-dev

- name: set ownership of virtual environments
  file:
    path: "{{ item.path }}/.venv-ansible"
    state: directory
    recurse: yes
    owner: "{{ item.pw_name }}"
    group: "{{ item.gr_name }}"
  become: true
  loop: "{{ home_dirs.files }}"
  loop_control:
    label: "{{ item.path }}/.venv-ansible"
