---
- name: Converge
  hosts: all
  vars:
    ansible_python_interpreter: auto_silent
    pip_packages:
      - setuptools
      - ansible[azure]==2.8.0
      - molecule==2.20
      - pywinrm>=0.3.0
  roles:
    - role: ansible-role-ansible-dev
