---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ansible-dev-${MOLECULE_DISTRO:-debian9}
    box: geerlingguy/${MOLECULE_DISTRO:-debian9}
    memory: 512
    cpus: 1
provisioner:
  name: ansible
verifier:
  name: testinfra
  options:
    v: 1
    s: true
