---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: false
platforms:
  - name: ansible-role-ansible-dev
    box: geerlingguy/debian9
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: false
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: false
  options:
    v: 1
