---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: true
platforms:
  - name: ansible-dev-${MOLECULE_DISTRO:-debian9}
    box: geerlingguy/${MOLECULE_DISTRO:-debian9}
    memory: 512
    cpus: 1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
verifier:
  name: testinfra
  lint:
    name: flake8
    enabled: true
  options:
    v: 1
    s: true
