---
- name: Prepare
  hosts: all
  vars:
    ansible_python_interpreter: auto_silent

  tasks:
  - name: add test developers
    user:
      name: "{{ item }}"
    loop:
      - johndoe
      - janedoe
    become: true
